#\DeclareLyXModule{Lecture design (Vietnamese translation)}
#\DeclareCategory{Maths}
#DescriptionBegin
#Vietnamese translation of the lecture design module.
#DescriptionEnd

# Author: Hung Nguyen <ndgnuh@protonmail.com>

Preamble
    \usepackage{lecture-design}
    \def\problemname{Bài tập}
    \def\definitionname{Định nghĩa}
    \def\theoremname{Định lý}
    \def\proofname{Chứng minh}
    \def\solutionname{Lời giải}
    \def\remarkname{Chú ý}
    \def\examplename{Ví dụ}
    \def\TypesetProofSection#1{Chứng minh cho \S#1}
    \def\TypesetSolutionSection#1{Lời giải cho~#1}
    \def\ProofHintText#1{Xem chứng minh ở trang #1}
    \SetMarkLabel{SolutionHint}{Giải:~tr.\,}
    \SetMarkLabel{ProofHint}{C/M:~tr.\,}
    \SetMarkLabel{Example}{Ví dụ}
    \SetMarkLabel{Quick}{Chữa nhanh}
    \SetMarkLabel{Answer}{Ans:~}
    \SetMarkLabel{Official index}{Index:~}
    \SetMarkLabel{MustDo}{Nên chữa}
    \SetMarkLabel{Danger}{[!]~}
EndPreamble

Style Definition
	LabelString "Định nghĩa \thedefinition. "
End 

Style Problem
	LabelString "Bài tập \theproblem. "
End 

Style Solution
	LabelString "Lời giải. "
End 

Style Proof
	LabelString "Chứng minh. "
End 

Style "Proof (Direct)"
	LabelString "Chứng minh (viết luôn). "
End 

Style Theorem
	LabelString "Định lý \thetheorem. "
End

Style Example
	LabelString "Ví dụ \theexample. "
End

Style Remark
    LabelString "Chú ý. "
End


InsetLayout "Flex:Example mark|E"
	LabelString			"Ví dụ"
End

InsetLayout "Flex:Quick mark|Q"
    LabelString			"Chữa nhanh"
End

InsetLayout "Flex:Answer mark|A"
    LabelString			"Đáp án"
End

InsetLayout "Flex:Official index mark|I"
    LabelString			"Index"
End

InsetLayout "Flex:Must-do mark|M"
    LabelString			"Nên chữa"
End

InsetLayout "Flex:Danger mark|D"
    LabelString			"Nguy hiểm"
End
